#include "annotation/intention.h"
#include "annotation/overview.h"
#include "database/db_provider.h"

#include <stddef.h>
#include <string.h>

;;OVERVIEW
/**
 * ============================================================================
 * CLASS: DbProvider (database/db_provider)
 * with zero code changes: edit rows, never touch logic)
 * ============================================================================
 * The database data-source directory: 25 static descriptor rows covering
 * the databases with complete driver support (JetBrains data-source
 * dialog, "_docs/fop.png"), each with a canonical slug, verbatim display
 * name, driver/engine key, canonical wire port, coarse wire family, and
 * an optional note. One table, linear lookups, zero allocation,
 * immutable (thread-safe reads without locks).
 *
 * STRUCT FIELDS (Mirroring database/db_provider.h — exactly this file's
 * class):
 * ----------------------------------------------------------------------------
 *   uint32_t reserved;   // singleton marker; no mutable state — all data
 *                        // lives in the static const DbProviderSlot rows
 *
 * SLOT RECORD (DbProviderSlot — Rule 3 co-location, zero behavior of its
 * own; all query behavior hangs off this table class):
 * ----------------------------------------------------------------------------
 *   const char *slug;         // canonical key, e.g. "postgresql"
 *   const char *displayName;  // verbatim source, e.g. "PostgreSQL"
 *   const char *engine;       // driver/engine key, e.g. "postgres"
 *   uint16_t defaultPort;     // canonical wire port; 0 = embedded/SDK-only
 *   DbProviderFamily family;  // coarse wire bucket
 *   const char *note;         // caveat; NULL when none
 *
 * PRIVATE HELPERS (generated data — each row carries exactly the SLOT
 * RECORD fields above; the fragment is included ONLY by this file):
 * ----------------------------------------------------------------------------
 *   kDbProviders[] — src/database/data/db_providers.inc (25 rows,
 *                    generated by tools/gen_db_providers.py; alphabetical,
 *                    clipped at PostgreSQL pending the owner)
 *
 * FUNCTION REGISTRY:
 * ----------------------------------------------------------------------------
 * Constructor:
 *   - DbProvider_shared()  : returns the singleton directory handle
 *
 * Core Functions:
 *   - DbProvider_count(self)              : total rows (25)
 *   - DbProvider_at(self, i)              : row at index i
 *   - DbProvider_get(self, slug)          : row by slug
 *   - DbProvider_findByEngine(self, engine) : first row by engine key
 *
 * Getters (Rule 24; null-safe. Setters omitted — immutable rows, waiver):
 *   - DbProvider_getSlug / getDisplayName / getEngine / getDefaultPort /
 *     getFamily / getNote(self, slot)
 * ============================================================================
 */
;;INTENTION("directory database/ holds adapter descriptors only: driver/engine keys + wire ports for future connectors; real drivers/engines live outside api-haven with zero includes — preferences.md Rule 17 api-haven clause")
;;INTENTION("source image clipped at PostgreSQL (P) — Q-Z rows are not invented; appended when the owner scrolls the dialog (see tools/gen_db_providers.py banner)")
;;INTENTION("immutable slot records — setters omitted; data is static const; access via DbProvider_* table functions — Rule 33 Tier-2 waiver")

#include "database/data/db_providers.inc"

static const uint32_t kDbProviderCount =
    (uint32_t)(sizeof(kDbProviders) / sizeof(kDbProviders[0]));

static DbProvider sDbProviderShared; // zero-init singleton

// CONSTRUCTORS

DbProvider *DbProvider_shared(void) {
    return &sDbProviderShared;
}

// CORE FUNCTIONS

uint32_t DbProvider_count(const DbProvider *self) {
    if (!self)
        return 0;
    return kDbProviderCount;
}

const DbProviderSlot *DbProvider_at(const DbProvider *self, uint32_t i) {
    if (!self || i >= kDbProviderCount)
        return nullptr;
    return &kDbProviders[i];
}

const DbProviderSlot *DbProvider_get(const DbProvider *self, const char *slug) {
    if (!self || !slug || (*slug) == '\0')
        return nullptr;
    for (uint32_t i = 0; i < kDbProviderCount; i++) {
        if (kDbProviders[i].slug && strcmp(kDbProviders[i].slug, slug) == 0)
            return &kDbProviders[i];
    }
    return nullptr;
}

const DbProviderSlot *DbProvider_findByEngine(const DbProvider *self,
                                              const char *engine) {
    if (!self || !engine || (*engine) == '\0')
        return nullptr;
    for (uint32_t i = 0; i < kDbProviderCount; i++) {
        if (kDbProviders[i].engine && strcmp(kDbProviders[i].engine, engine) == 0)
            return &kDbProviders[i];
    }
    return nullptr;
}

// GETTERS

const char *DbProvider_getSlug(const DbProvider *self, const DbProviderSlot *slot) {
    (void)self;
    return slot ? (*slot).slug : nullptr;
}

const char *DbProvider_getDisplayName(const DbProvider *self, const DbProviderSlot *slot) {
    (void)self;
    return slot ? (*slot).displayName : nullptr;
}

const char *DbProvider_getEngine(const DbProvider *self, const DbProviderSlot *slot) {
    (void)self;
    return slot ? (*slot).engine : nullptr;
}

uint16_t DbProvider_getDefaultPort(const DbProvider *self, const DbProviderSlot *slot) {
    if (!self || !slot)
        return 0;
    return (*slot).defaultPort;
}

DbProviderFamily DbProvider_getFamily(const DbProvider *self, const DbProviderSlot *slot) {
    if (!self || !slot)
        return DB_PROVIDER_FAMILY_SQL; // safe default
    return (*slot).family;
}

const char *DbProvider_getNote(const DbProvider *self, const DbProviderSlot *slot) {
    (void)self;
    return slot ? (*slot).note : nullptr;
}
